name: SwiftHomes
version: '1.0.0'
main: com.homes.plugin.HomePlugin
api-version: '1.21'
folia-supported: true
author: YourName
description: Essentials-type home plugin with chest GUI

commands:
  sethome:
    description: Open GUI to set a home
    usage: /sethome [name]
    permission: swifthomes.sethome
  home:
    description: Teleport to a home or open GUI to select
    usage: /home [name]
    permission: swifthomes.home
  delhome:
    description: Delete a home or open GUI to select
    usage: /delhome [name]
    permission: swifthomes.delhome
  homes:
    description: List all your homes. Use '/homes help' for detailed help or '/homes reload' to reload messages
    usage: /homes [help|reload]
    permission: swifthomes.homes

permissions:
  swifthomes.sethome:
    description: Allows players to set homes
    default: true
  swifthomes.home:
    description: Allows players to teleport to homes
    default: true
  swifthomes.delhome:
    description: Allows players to delete homes
    default: true
  swifthomes.homes:
    description: Allows players to list homes
    default: true
  swifthomes.unlimited:
    description: Allows unlimited homes
    default: op
  swifthomes.homes.1:
    description: Allows 1 home
    default: false
  swifthomes.homes.2:
    description: Allows 2 homes
    default: false
  swifthomes.homes.3:
    description: Allows 3 homes
    default: false
  swifthomes.homes.4:
    description: Allows 4 homes
    default: false
  swifthomes.homes.5:
    description: Allows 5 homes
    default: false
  swifthomes.homes.10:
    description: Allows 10 homes
    default: false
  swifthomes.homes.15:
    description: Allows 15 homes
    default: false
  swifthomes.homes.20:
    description: Allows 20 homes
    default: false
  swifthomes.homes.25:
    description: Allows 25 homes
    default: false
  swifthomes.homes.50:
    description: Allows 50 homes
    default: false
  swifthomes.admin:
    description: Allows reloading messages and other admin functions
    default: op
